# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'cucumber'
gem 'rspec'
gem 'capybara'
gem 'selenium-webdriver'
gem 'site_prism'
gem 'data_magic'
gem 'report_builder'